Repository kiwiproject/kiwi-bom, pull requests merged in 2022-04, with the labels that each got.

#140 Bump metrics from 4.1.29 to 4.1.31
  pom.xml
Labels: dependencies

#141 Bump jetty from 9.4.44.v20210927 to 9.4.46.v2022033
  pom.xml
Labels: dependencies

#142 Add comments to BOM explaining several "odd" dependencies
  pom.xml
Labels: documentation

#143 Fix jetty version
  pom.xml
Labels: dependencies

#149 Add new dependencies to fix downstream convergence errors
  pom.xml
Labels: dependencies

#179 Revert latest spring-data-mongodb and mongo-driver-xxx versions
  pom.xml
Labels: bug, dependencies

#190 Updated to build with Java 17 temurin
  .github/workflows/build.yml
Labels: github_actions
